services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: database-user
      POSTGRES_PASSWORD: database-password
      POSTGRES_DB: local-database
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: {}
